version: '3'

services:
  php:
    container_name: php
    build: ./configs/php
    volumes:
      - ./code:/workspace

  nginx1:
    container_name: nginx1
    depends_on:
      - php
    image: nginx:latest
    links:
      - php
    volumes:
      - ./configs/nginx/bin:/scripts:ro
      - ./configs/nginx/conf:/etc/nginx/conf.d
      - ./code:/workspace
    command: /bin/sh /scripts/run.sh
    ports:
      - 8080:80
    environment:
      FPM_BACKEND: php

  nginx2:
    container_name: nginx2
    depends_on:
      - php
    image: nginx:latest
    links:
      - php
    volumes:
      - ./configs/nginx/bin:/scripts:ro
      - ./configs/nginx/conf:/etc/nginx/conf.d
      - ./code:/workspace
    command: /bin/sh /scripts/run.sh
    ports:
      - 8081:80
    environment:
      FPM_BACKEND: php


  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./configs/varnish/varnish.vcl:/etc/varnish/default.vcl"
    depends_on:
      - nginx
    links:
      - nginx
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=1G
    command: "-p default_keep=300"
    ports:
      - 80:80
